version: '3.4'

services:
  checkout.paymentgateway.api:
    image: ${DOCKER_REGISTRY-}checkoutpaymentgatewayapi
    build:
      context: .
      dockerfile: Checkout.PaymentGateway.Api/Dockerfile
    depends_on:
      - checkout.paymentgateway.mongo

  checkout.paymentgateway.mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  checkout.paymentgateway.mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - checkout.paymentgateway.mongo