using System.Net;

namespace Checkout.PaymentGateway.Api.Application
{
    /// <summary>
    /// A model of a possible bank response.
    /// </summary>
    /// <typeparam name="T">The reponse object type.</typeparam>
    public class BankResponse<T>
    {
        /// <summary>
        /// A response object from the bank service.
        /// </summary>
        public T Response { get; set; }

        /// <summary>
        /// A status code generated by the bank service.
        /// </summary>
        public HttpStatusCode StatusCode { get; set; }
    }
}
